name: Update DEV Templates

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  update:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and run update script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST_DEV}}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.DEPLOY_KEY_DEV }}
          passphrase: ${{ secrets.DEPLOY_KEY_PASS_DEV }}
          script: bash /opt/sapa/scripts/updateTemplates.sh
          
